spring:
  datasource:
    url: jdbc:mysql://sweet-home-database.cimib5bfddhg.us-east-1.rds.amazonaws.com/booking-service-db?createDatabaseIfNotExist=true
    username: admin
    password: DmHQfDhChM3DCbObaNry
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: BOOKING-SERVICE

server:
  port: 8080

paymentService:
  transactionUrl: http://PAYMENT-SERVICE/transaction

notificationService:
  kafkaServerValue: ec2-user@ec2-52-7-133-91.compute-1.amazonaws.com:9092
  sentKafkaTopic: message

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  
  instance:
    hostname: localhost
